controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    effort_controller:
      type: effort_controllers/JointGroupEffortController

    control_pad_controller:
      type: control_pad/ControlPadController

gpio_controller:
  ros__parameters:
    type: gpio_controllers/GpioCommandController
    gpios:
      - beckhoff_output
      - beckhoff_input
    command_interfaces:
      beckhoff_output:
        - interfaces:
          - d_1
          - d_2
          - d_3
          - d_4
          - d_5
          - d_6
          - d_7
          - d_8
          - d_9
          - d_10
          - d_11
          - d_12
          - d_13
          - d_14
          - d_15
          - d_16

    state_interfaces:
      beckhoff_input:
        - interfaces:
          - d_1
          - d_2
          - d_3
          - d_4
          - d_5
          - d_6
          - d_7
          - d_8

trajectory_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
    joints:
      - joint2
      # - joint3
      # - joint4
      # - joint5

velocity_controller:
  ros__parameters:
    joints:
      - joint2

effort_controller:
  ros__parameters:
    joints:
      - joint2

control_pad_controller:
  ros__parameters:
    joints:
      - joint2
      # - joint3
      # - joint4
      # - joint5
      # - joint6
    command_interfaces:
      - position
      - velocity
      - mode

    state_interfaces:
      - position
      - velocity
      - mode